import {
  Box,
  Container,
  Heading,
  Text,
  Button,
  VStack,
  HStack,
  SimpleGrid,
  Icon,
  Flex,
} from '@chakra-ui/react';
import { Link as RouterLink } from 'react-router-dom';
import { FaRocket, FaBrain, FaChartLine, FaLightbulb, FaArrowRight } from 'react-icons/fa';
import { motion } from 'framer-motion';

const MotionBox = motion(Box);

const features = [
  {
    icon: FaBrain,
    title: 'AI-Powered Learning Paths',
    description: 'Get personalized roadmaps generated by AI based on your current skills and goals.',
  },
  {
    icon: FaChartLine,
    title: 'Track Your Progress',
    description: 'Mark topics as complete and visualize your learning journey week by week.',
  },
  {
    icon: FaLightbulb,
    title: 'Smart Resource Suggestions',
    description: 'AI generates optimal search strings to find the best learning resources.',
  },
  {
    icon: FaRocket,
    title: 'Quiz Yourself',
    description: 'Test your knowledge with AI-generated quizzes at the end of each week.',
  },
];

const HomePage = () => {
  return (
    <Box>
      {/* Hero Section */}
      <Box
        minH="90vh"
        display="flex"
        alignItems="center"
        position="relative"
        overflow="hidden"
      >
        {/* Background gradient */}
        <Box
          position="absolute"
          top="50%"
          left="50%"
          transform="translate(-50%, -50%)"
          width="150%"
          height="150%"
          bgGradient="radial(circle at center, brand.500 0%, transparent 50%)"
          opacity={0.1}
          filter="blur(80px)"
        />

        <Container maxW="container.xl" position="relative">
          <VStack spacing={8} textAlign="center" py={20}>
            <MotionBox
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Heading
                as="h1"
                size="3xl"
                bgGradient="linear(to-r, brand.400, accent.400)"
                bgClip="text"
                lineHeight="shorter"
              >
                Your Personalized
                <br />
                Learning Journey Starts Here
              </Heading>
            </MotionBox>

            <MotionBox
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              <Text fontSize="xl" color="gray.400" maxW="2xl">
                Tell us what you know and where you want to go. Our AI will create a
                structured, week-by-week learning path tailored just for you.
              </Text>
            </MotionBox>

            <MotionBox
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              <HStack spacing={4}>
                <Button
                  as={RouterLink}
                  to="/register"
                  size="lg"
                  colorScheme="blue"
                  rightIcon={<FaArrowRight />}
                >
                  Start Learning
                </Button>
                <Button
                  as={RouterLink}
                  to="/login"
                  size="lg"
                  variant="outline"
                  borderColor="whiteAlpha.400"
                  color="white"
                  _hover={{ bg: 'whiteAlpha.100' }}
                >
                  I have an account
                </Button>
              </HStack>
            </MotionBox>
          </VStack>
        </Container>
      </Box>

      {/* Features Section */}
      <Box py={20} bg="blackAlpha.300">
        <Container maxW="container.xl">
          <VStack spacing={12}>
            <VStack spacing={4} textAlign="center">
              <Heading size="xl">How It Works</Heading>
              <Text color="gray.400" maxW="xl">
                Our AI analyzes your skills and goals to create a structured learning path
                with clear milestones and progress tracking.
              </Text>
            </VStack>

            <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} spacing={8} w="full">
              {features.map((feature, index) => (
                <MotionBox
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                >
                  <Flex
                    direction="column"
                    align="center"
                    textAlign="center"
                    p={6}
                    bg="whiteAlpha.50"
                    borderRadius="xl"
                    border="1px solid"
                    borderColor="whiteAlpha.100"
                    _hover={{
                      bg: 'whiteAlpha.100',
                      transform: 'translateY(-4px)',
                      boxShadow: 'xl',
                    }}
                    transition="all 0.3s"
                  >
                    <Icon as={feature.icon} boxSize={10} color="brand.400" mb={4} />
                    <Heading size="md" mb={2}>
                      {feature.title}
                    </Heading>
                    <Text color="gray.400" fontSize="sm">
                      {feature.description}
                    </Text>
                  </Flex>
                </MotionBox>
              ))}
            </SimpleGrid>
          </VStack>
        </Container>
      </Box>

      {/* CTA Section */}
      <Box py={20}>
        <Container maxW="container.md" textAlign="center">
          <VStack spacing={6}>
            <Heading size="xl">Ready to accelerate your learning?</Heading>
            <Text color="gray.400">
              Join thousands of learners who have transformed their skills with AI-powered learning paths.
            </Text>
            <Button
              as={RouterLink}
              to="/register"
              size="lg"
              colorScheme="blue"
              rightIcon={<FaArrowRight />}
            >
              Create Your Free Account
            </Button>
          </VStack>
        </Container>
      </Box>
    </Box>
  );
};

export default HomePage;
